Lite version of the key and seed for the lite client
Holo-Host/dpki-lite.js pull request #2
Opened 2019-01-30 07:31 UTC by zo-el

2019-01-30 15:31 UTC, neonphog commented on README.md
> +[![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](http://www.gnu.org/licenses/gpl-3.0)
Network / crypto libs that we want to be eminently shareable should be Apache-2.0, not GPL imho. see mm convo https://chat.holochain.net/holo/pl/a6587bueyffxxmm46st39mdo3w related to https://github.com/holochain/n3h/pull/24

2019-01-30 15:48 UTC, neonphog commented on packages/dpki-lite/lib/util.js
> +    return sodium.to_base64(Buffer.concat([signPub, encPub]))
How are these being rolled up for the browser? Is there a "Buffer" shim or something? Might be better to stick with browser ArrayBuffers + friends.

2019-01-30 15:51 UTC, neonphog commented on packages/dpki-lite/lib/util.js
> +    return sodium.to_base64(Buffer.concat([signPub, encPub]))
We need this to generate identical IDs to the core code, including the prefix multihash bytes and suffix reed-solomon parity bytes.

https://github.com/holochain/n-bch-rs/blob/master/rust/build.sh#L5 is currently building a nodejs target... wasm-bindgen can also build a web target... so we might need to start there with it putting the nodejs build in the `lib` directory, and building the web target into a `browser` directory... Some day it'd be nice to figure out how to make wasm-bindgen make a unified target for both environments.

2019-01-30 15:54 UTC, neonphog requested changes
What's the state of the art for browser unit testing these days? Is it still http://phantomjs.org/ ? I've been out of the web-world for a while. I'd like to see this project built up with some kind of browser bundling (webpack, rollup, or whatever we think we might be using) and run through some testing that can be integrated into CI

2019-01-30 15:59 UTC, neonphog commented
apparently you can use chromium? https://medium.com/@metalex9/replace-phantomjs-with-headless-chromium-for-javascript-unit-testing-in-karma-59812e6f8ce4

2019-01-30 19:02 UTC, zo-el commented on README.md
> +[![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](http://www.gnu.org/licenses/gpl-3.0)
Done

2019-01-31 01:23 UTC, peeech reviewed
Do we need this try-catch block?

2019-01-31 01:23 UTC, peeech commented on packages/dpki-lite/lib/seed.js
> +    try {
Seems like this try-catch block is unnecessary. It will intercept meaningful errors inside of it...

2019-01-31 01:23 UTC, peeech commented on packages/dpki-lite/lib/seed.js
> +      throw new Error('`Error Throwen: seed` must be a 16/32 byte Buffer or 24 word bip39 mnemonic string')
... and always throw the same error

2019-01-31 07:01 UTC, zo-el commented on packages/dpki-lite/lib/seed.js
> +    try {
It's just an oversite. Thanks for catching that :smile: 
I made the necessary changes

2019-02-05 05:00 UTC, zo-el commented on packages/dpki-lite/lib/util.js
> +    return sodium.to_base64(Buffer.concat([signPub, encPub]))
Hi @neonphog, I tried out the bundling it with Buffers and it can successfully be rolled up. Do you think I should still change it?

2019-02-05 05:07 UTC, zo-el commented
HI Guys, I have updated this branch to be able to bundle and run on a browser

2019-02-06 23:09 UTC, neonphog commented on packages/dpki-lite/lib/util.js
> +    return sodium.to_base64(Buffer.concat([signPub, encPub]))
If it works, I'm cool with it :+1:

2019-03-04 05:44 UTC, merged